#!/usr/bin/env bash
# This script prints numbers 1-20 with bad luck messages for 4, 9, and 17 using case
i=1
while [ "$i" -le 20 ]
do
  case $i in
    4)
      echo "$i"
      echo "bad luck from China"
      ;;
    9)
      echo "$i"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$i"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  i=$((i+1))
done
